### PR TITLE
Organize frontend

### LINKED ISSUE #810: Frontend code organization
The frontend code files aren't organized as well as they could be and are illogical in places, e.g., grade upload dialogs should not be under `course-view`.

### PR DESCRIPTION
**Pull request by bntti**
**Description of changes**
- [x] Organize frontend files
- [x] Fix error caused by `UserButton`

**Related issues**
Closes #810

### CODE REVIEW

**Review by gubo97000 — APPROVED** [review]
lgtm, I see a lot of "../" should we create some aliases for paths?

**Review by no-comma — COMMENTED** [review]
Some comments:
- `front-page/users/UsersView.tsx` should be renamed?
- `graph` has quite a lot of files, it could have a `node` subdirectory
- `alerts` could be under `shared`, `graph` is also shared(?) but I think it's large enough to justify being directly under `components`
- `auth/UserButton.tsx` and `shared/LanguageSelectButton.tsx` are both header elements, potentially these could be grouped together

**Comment by bntti** [comment]
> lgtm, I see a lot of "../" should we create some aliases for paths?

I could add `@/=./src/` and then use absolute paths for everything. (the common imports would still work normally)

**Comment by bntti** [comment]
> Some comments:
> 
>     * `front-page/users/UsersView.tsx` should be renamed?
> 
>     * `graph` has quite a lot of files, it could have a `node` subdirectory
> 
>     * `alerts` could be under `shared`, `graph` is also shared(?) but I think it's large enough to justify being directly under `components`
> 
>     * `auth/UserButton.tsx` and `shared/LanguageSelectButton.tsx` are both header elements, potentially these could be grouped together

Good points. Implemented.

**Review by no-comma — APPROVED** [review]

**Comment by gubo97000** [comment]
Adding this to vscode settings fixes the missing warning, let me know if I broke something else
```json
  "eslint.workingDirectories": [
    {"mode": "auto"}
  ] 
```

**Pull request merged**
